export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const UPLOAD_FILES = 'UPLOAD_FILES';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';

export const DOWNLOAD_GALLERY = 'DOWNLOAD_GALLERY';
export const DOWNLOAD_GALLERY_SUCCESS = 'DOWNLOAD_GALLERY_SUCCESS';
export const DOWNLOAD_GALLERY_FAILURE = 'DOWNLOAD_GALLERY_FAILURE';

export const DOWNLOAD_GALLERIES = 'DOWNLOAD_GALLERIES';
export const DOWNLOAD_GALLERIES_SUCCESS = 'DOWNLOAD_GALLERIES_SUCCESS';
export const DOWNLOAD_GALLERIES_FAILURE = 'DOWNLOAD_GALLERIES_FAILURE';

export const RESET_STATE = 'RESET_STATE';
